insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('B', 'Audiovisuel');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('K', 'Carte');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('O', 'Doc Elec');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('N', 'Enregistrement');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('I', 'Image');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('F', 'Manuscrit');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('Z', 'Multimédia');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('V', 'Objet');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('G', 'Musique');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('M', 'Partition');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('BD', 'Ressource continue');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('A', 'Monographie');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('PC', 'Partie composante');

insert into RULESSET(RULESET_ID, LIBELLE) values (1, 'Données codées (1XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (2, 'Indexation-matière (6XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (3, 'Liens ($0/$3)');
insert into RULESSET(RULESET_ID, LIBELLE) values (4, 'Informations descriptives (2XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (5, 'Translittération ($6/$7)');
insert into RULESSET(RULESET_ID, LIBELLE) values (6, 'Dates');
insert into RULESSET(RULESET_ID, LIBELLE) values (7, 'Responsabilités (7XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (5, 'Nouvelles implémentations Unimarc');