insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('B', 'Audiovisuel');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('K', 'Carte');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('O', 'Doc Elec');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('N', 'Enregistrement');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('I', 'Image');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('F', 'Manuscrit');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('Z', 'Multimédia');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('V', 'Objet');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('G', 'Musique');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('M', 'Partition');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('BD', 'Ressource continue');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('A', 'Monographie');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('TS', 'Thèse soutenance');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('TR', 'Thèse reproduction');

insert into RULESSET(RULESET_ID, LIBELLE) values (1, 'Zones 210/214 (publication, production, diffusion)');
insert into RULESSET(RULESET_ID, LIBELLE) values (2, 'Implémentations UNM 2022');
insert into RULESSET(RULESET_ID, LIBELLE) values (3, 'Translittération (présence $6, $7)');
insert into RULESSET(RULESET_ID, LIBELLE) values (4, 'Zones de données codées (1XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (5, 'Zones d''indexation-matière (6XX)');