insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('B', 'Audiovisuel');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('K', 'Carte');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('O', 'Doc Elec');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('N', 'Enregistrement');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('I', 'Image');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('F', 'Manuscrit');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('Z', 'Multimédia');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('V', 'Objet');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('G', 'Musique');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('M', 'Partition');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('BD', 'Ressource continue');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('A', 'Monographie');
insert into FAMILLEDOCUMENT(FAMILLEDOCUMENT_ID, LIBELLE) values ('PC', 'Partie composante');

insert into RULESSET(RULESET_ID, LIBELLE) values (1, 'Données codées (1XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (2, 'Indexation-matière (6XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (3, 'Liens ($0/$3)');
insert into RULESSET(RULESET_ID, LIBELLE) values (4, 'Informations descriptives (2XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (5, 'Translittération ($6/$7)');
insert into RULESSET(RULESET_ID, LIBELLE) values (6, 'Dates');
insert into RULESSET(RULESET_ID, LIBELLE) values (7, 'Responsabilités (7XX)');
insert into RULESSET(RULESET_ID, LIBELLE) values (8, 'Nouvelles implémentations Unimarc');
insert into RULESSET(RULESET_ID, LIBELLE) values (9, 'Identification (0XX)');

insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '200');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '205');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '206');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '207');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '208');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '214');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('2XX', '225');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '413');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '421');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '422');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '423');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '424');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '425');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '430');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '431');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '432');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '433');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '434');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '435');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '436');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '437');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '440');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '441');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '442');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '443');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '444');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '445');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '446');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '447');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '448');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '451');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '452');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '453');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '454');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '455');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '456');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '461');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '463');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '464');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '470');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '481');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '482');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('4XX', '488');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '500');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '501');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '503');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '510');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '512');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '513');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '514');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '515');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '516');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '517');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '518');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '520');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '530');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '531');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '532');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '540');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '541');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '545');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('5XX', '579');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '600');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '601');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '602');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '604');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '605');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '606');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '607');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('6XX', '608');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '700');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '701');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '702');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '710');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '711');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '712');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '720');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '721');
insert into ZONE_GENERIQUE(ZONE_GENERIQUE, ZONE) values('7XX', '722');
